dependencies:
- name: amazed-arachnid
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: apparent-baboon
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: classic-fawn
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: destined-anchovy
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: driven-condor
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: easy-sailfish
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: generous-poodle
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: jxui-backend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: jxui-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: keen-halibut
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: leading-bluebird
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: loyal-seasnail
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: model-fly
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: moral-pika
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: relevant-arachnid
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rich-bass
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: touched-walleye
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: wondrous-akita
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
