dependencies:
- name: absolute-oryx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: amazed-arachnid
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: amazing-marmoset
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: apparent-baboon
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: arriving-anchovy
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: calm-muskrat
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: central-hawk
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: classic-fawn
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: clever-dogfish
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: cool-mite
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: destined-anchovy
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: driven-condor
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: easy-sailfish
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: endless-viper
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: evolving-caribou
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: fleet-phoenix
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: generous-poodle
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: gorgeous-orca
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: growing-kid
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: intent-fawn
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: intimate-lionfish
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: jxui-backend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: jxui-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: keen-halibut
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: leading-bluebird
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: loved-fawn
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: loyal-seasnail
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: model-fly
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: moral-pika
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: neat-insect
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: noble-crane
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: pretty-cockatoo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rare-moose
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: relevant-arachnid
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rested-seasnail
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: rich-bass
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: sterling-lionfish
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: touched-walleye
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: wealthy-cod
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: wondrous-akita
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
